require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  SuggestExtensions: false
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Bundler/GemComment:
  Enabled: false
Bundler/GemVersion:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Rails/SchemaComment:
  Enabled: false


Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 50
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 3
